### PR TITLE
add group multifiltering, group data-label and data parameter in filtering event

### LINKED ISSUE #20: Inclusive/Excluse filtering mode
hello
I have a few data-multifilter
sample

```
<ul>
   <li data-multifilter="1"> Green </li>
   <li data-multifilter="2"> Orange </li>
   <li data-multifilter="3"> Purple </li>
</ul>
<ul>
   <li data-multifilter="4"> text1 </li>
   <li data-multifilter="5"> text2</li>
   <li data-multifilter="6"> text3</li>
</ul>

```

And i have some blocks

```
<div class="filtr-container">
    <div class="filtr-item" data-category="1,2,4" data-author="John Doe" data-year="1998" data-novel="Cool book 1">
       <img src="img/sample.jpg" alt="sample">
    </div>
    <div class="filtr-item" data-category="1,3,5" data-author="Jane Doe" data-year="2003" data-novel="Cooler book">
       <img src="img/sample.jpg" alt="sample">
    </div>
    <div class="filtr-item" data-category="4,6" data-author="Jake Doe" data-year="2008" data-novel="Coolest book">
       <img src="img/sample.jpg" alt="sample">
    </div>
</div>
```

in defaul mode if i choice category 1 and 4 Filtterzr result 1 OR 4.  But i need 1 AND 4. I need result only data-category="1,2,4" 

is there any option to set the sampling algorithm? some INCLUSIVE/EXCLISIVE mode... like this http://wch.io/projects/tagsort/demo-stacks/

### PR DESCRIPTION
**Pull request by xileftenurb**
hello,

this pull request fix #20 and #6 by adding a whole new feature : group multifiltering

I added some documentation and tutorial about the new feature in the readme, but feel free to add them to your website.

the feature could be further enhanced, but that was all the time I had to work on this.

I hope it help other.

### CODE REVIEW

**Comment by giotiskl** [comment]
@xileftenurb thanks for the contribution will evaluate during the weekend and merge

**Comment by xileftenurb** [comment]
I added a new non-breaking-feature : data in filtering event and callback.
I also fixed some bug with group mode and with filteringStart event firing multiple time for a single click.

**Comment by xileftenurb** [comment]
Oh, and I just fixed #55 with a little regex : "/\s*,\s*/
it permit any number of space before and after each "," separator.

**Comment by xileftenurb** [comment]
the last commit add two new feature :
first, the possibility to initialise filterizr with filter in toggle and group mode (previously, only "active" mode could have a starting filter)
second, add a third callback argument to onFilteringStart, activeElement, the array of active DOM element after the new filter are applied.

this should be the last feature I add for the moment, my actual project now have all it need to work as expected.

**Comment by xileftenurb** [comment]
@giotiskl any new on this pull request?

**Comment by giotiskl** [comment]
@xileftenurb will merge PR and publish patch end of July. I am on holidays until then with no laptop.

**Comment by lenamtl** [comment]
@giotiskl  Any news about this PR?
@xileftenurb Do you have any Jsfiddle to show a working example of the new feature?

**Comment by xileftenurb** [comment]
@lenamtl I don't have any Jsfiddle to show at the moment. I will try to do one when I will have some time.

**Comment by giotiskl** [comment]
This PR is now unfortunately redundant despite the really good work done.

This is due to the decision to rewrite the core of Filterizr to make the code more maintainable, readable and up to date with the best practices.

The core is now rewritten in ES6, with Webpack & Babel and test cases are implemented in Jest as well as ESLint support.

Nevertheless thank you for the time taken to prepare this PR, I'd be happy to see more work of you in the future. complying with the latest rewrite of Filterizr :)

**Pull request closed without merging**
