### PR TITLE
Public function for appending elements

### PR DESCRIPTION
**Pull request by matmar-91**
This change adds ability to append new elements to gallery. In addition I've done some refactoring here and there. Here you can see a little demo of how this feature works: [http://filtrizr.marchel.it/](http://filtrizr.marchel.it/).
It's my attempt to resolving issue #13 
If you have any questions about changes I've made please ask.

### CODE REVIEW

**Comment by giotiskl** [comment]
@matmar-91 at first glance it looks quite good matmar! thank you for your contribution, I'll have to take a more extensive look at it at some point and then I'll merge, but you'll have to bear with me as I'm currently in the process of moving to another country and I have quite a lot on my plate! Keep it up though!  :+1:

**Comment by matmar-91** [comment]
No problem, take your time. :smile: 
I'll try too look into removing content when I get some free time. It shouldn't be hard to do.

**Comment by giotiskl** [comment]
Hello dear @matmar-91,
sorry for the massive delay but I have finally settled down and I will take a look in implementing these features during this weekend when I'll be releasing a new patch!

Did you by any chance look into adding a function to remove elements?

**Comment by vrusua** [comment]
Hi dear **@matmar-91** and **@giotiskl**,

thank your very much for the great update!

**@matmar-91**, can you please share your demo source? I found also the "Check to redo sorting after loading new data" works not as expected, the resorting by alphabet or mixed once the new data loaded. Is it possible to fix this? Thank you.

Cheers,
Ruslan

**Comment by giotiskl** [comment]
This PR is now unfortunately redundant despite the really good work done.

This is due to the decision to rewrite the core of Filterizr to make the code more maintainable, readable and up to date with the best practices.

The core is now rewritten in ES6, with Webpack & Babel and test cases are implemented in Jest as well as ESLint support.

Nevertheless thank you for the time taken to prepare this PR, I'd be happy to see more work of you in the future. complying with the latest rewrite of Filterizr :)

**Pull request closed without merging**
