### PR TITLE
Ignore dev files in published package

### PR DESCRIPTION
**Pull request by jariz**
These files are not used by library consumers and therefore should be ignored by the published files.
(I'm using babel from the project that consumes this library and babel attempts to use the .babelrc file, which is an option that can't be disabled - not in my setup, at least.)

Furthermore, I propose the following changes (which I'll make a separate PR for if agreed to):

- It is fairly common practice in the npm ecosystem to make your main entry point adhere to ES5 code with require calls for external dependencies.
I suggest pointing the main entry point to the compiled dist file.
- The reliance upon a global variable (`jQuery` & `$`) is making this project impossible/very hard to use when bundling [without explicit modifications to standard loader logic](https://medium.com/@stefanledin/webpack-2-jquery-plugins-and-imports-loader-e0d984650058).
I suggest adding `jquery` as a `peerDependency` and adding a import for it on the places the global var is referenced.
Additionally, an default export could be added to `src/index.js` that would be a patched version of jQuery with the filterizr plugin added to it.

### CODE REVIEW

**Comment by giotiskl** [comment]
@jariz I agree with your thoughts. 

Could you please set as the base to this and the future PR the develop branch? 

Once merged and tested I will then prepare a new version and merge to master.

**Comment by jariz** [comment]
Cool, base changed.

**Comment by giotiskl** [comment]
@jariz as an update, I am not aware if you got to start working on the rest of the changes you proposed, but as a matter of fact I implemented them myself, they're already on develop and coming in the next release tomorrow.

**Comment by jariz** [comment]
hiya @giotiskl, I haven't had the time yet myself, so thats awesome!

**Pull request merged**
